
package com.adaapa.tokenverifier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TokenVerifier", targetNamespace = "tokenverifier.adaapa.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TokenVerifier {


    /**
     * 
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "userObjectInJSON", targetNamespace = "")
    @RequestWrapper(localName = "verifyToken", targetNamespace = "tokenverifier.adaapa.com", className = "com.adaapa.tokenverifier.VerifyToken")
    @ResponseWrapper(localName = "verifyTokenResponse", targetNamespace = "tokenverifier.adaapa.com", className = "com.adaapa.tokenverifier.VerifyTokenResponse")
    @Action(input = "tokenverifier.adaapa.com/TokenVerifier/verifyTokenRequest", output = "tokenverifier.adaapa.com/TokenVerifier/verifyTokenResponse")
    public String verifyToken(
        @WebParam(name = "access_token", targetNamespace = "")
        String accessToken);

}
