
package com.adaapa.ojekservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OjekOnline", targetNamespace = "http://ojekservice.adaapa.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface OjekOnline {


    /**
     * 
     * @param accessToken
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/addUserRequest", output = "http://ojekservice.adaapa.com/OjekOnline/addUserResponse")
    public String addUser(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken,
        @WebParam(name = "user", partName = "user")
        String user);

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/getDriverProfileRequest", output = "http://ojekservice.adaapa.com/OjekOnline/getDriverProfileResponse")
    public String getDriverProfile(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken);

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/getProfileRequest", output = "http://ojekservice.adaapa.com/OjekOnline/getProfileResponse")
    public String getProfile(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken);

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/getPreferredLocationRequest", output = "http://ojekservice.adaapa.com/OjekOnline/getPreferredLocationResponse")
    public String getPreferredLocation(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken);

    /**
     * 
     * @param location
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/addPreferredLocationRequest", output = "http://ojekservice.adaapa.com/OjekOnline/addPreferredLocationResponse")
    public String addPreferredLocation(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken,
        @WebParam(name = "location", partName = "location")
        String location);

    /**
     * 
     * @param accessToken
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/editProfileRequest", output = "http://ojekservice.adaapa.com/OjekOnline/editProfileResponse")
    public String editProfile(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken,
        @WebParam(name = "user", partName = "user")
        String user);

    /**
     * 
     * @param driverName
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/findDriverRequest", output = "http://ojekservice.adaapa.com/OjekOnline/findDriverResponse")
    public String findDriver(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken,
        @WebParam(name = "driver_name", partName = "driver_name")
        String driverName);

    /**
     * 
     * @param destination
     * @param pickup
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/findDriverByPreferredLocationRequest", output = "http://ojekservice.adaapa.com/OjekOnline/findDriverByPreferredLocationResponse")
    public String findDriverByPreferredLocation(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken,
        @WebParam(name = "pickup", partName = "pickup")
        String pickup,
        @WebParam(name = "destination", partName = "destination")
        String destination);

    /**
     * 
     * @param accessToken
     * @param order
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/completeOrderRequest", output = "http://ojekservice.adaapa.com/OjekOnline/completeOrderResponse")
    public String completeOrder(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken,
        @WebParam(name = "order", partName = "order")
        String order);

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/getUserHistoryRequest", output = "http://ojekservice.adaapa.com/OjekOnline/getUserHistoryResponse")
    public String getUserHistory(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken);

    /**
     * 
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/getDriverHistoryRequest", output = "http://ojekservice.adaapa.com/OjekOnline/getDriverHistoryResponse")
    public String getDriverHistory(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken);

    /**
     * 
     * @param orderId
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/hideDriverHistoryRequest", output = "http://ojekservice.adaapa.com/OjekOnline/hideDriverHistoryResponse")
    public String hideDriverHistory(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken,
        @WebParam(name = "order_id", partName = "order_id")
        int orderId);

    /**
     * 
     * @param orderId
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/hideUserHistoryRequest", output = "http://ojekservice.adaapa.com/OjekOnline/hideUserHistoryResponse")
    public String hideUserHistory(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken,
        @WebParam(name = "order_id", partName = "order_id")
        int orderId);

    /**
     * 
     * @param position
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/deletePreferredLocationRequest", output = "http://ojekservice.adaapa.com/OjekOnline/deletePreferredLocationResponse")
    public String deletePreferredLocation(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken,
        @WebParam(name = "position", partName = "position")
        int position);

    /**
     * 
     * @param location
     * @param position
     * @param accessToken
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/editPreferredLocationRequest", output = "http://ojekservice.adaapa.com/OjekOnline/editPreferredLocationResponse")
    public String editPreferredLocation(
        @WebParam(name = "access_token", partName = "access_token")
        String accessToken,
        @WebParam(name = "position", partName = "position")
        int position,
        @WebParam(name = "location", partName = "location")
        String location);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ojekservice.adaapa.com/OjekOnline/findDriverByUsernameRequest", output = "http://ojekservice.adaapa.com/OjekOnline/findDriverByUsernameResponse")
    public String findDriverByUsername(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

}
